server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 20

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/project
    username: root
  application:
    name: AUTH-SERVICE
  jpa:
    hibernate:
      ddl-auto: update